import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'aboutPage',
  title: 'About Page',
  type: 'document',
  fields: [
    defineField({ name: 'heroHeading', title: 'Hero Heading (EN)', type: 'string' }),
    defineField({ name: 'heroHeadingLv', title: 'Hero Heading (LV)', type: 'string' }),
    defineField({ name: 'heroSubtitle', title: 'Hero Subtitle (EN)', type: 'string' }),
    defineField({ name: 'heroSubtitleLv', title: 'Hero Subtitle (LV)', type: 'string' }),
    defineField({ name: 'storyHeading', title: 'Our Story Heading (EN)', type: 'string' }),
    defineField({ name: 'storyHeadingLv', title: 'Our Story Heading (LV)', type: 'string' }),
    defineField({ name: 'storyText', title: 'Our Story Text (EN)', type: 'text', rows: 8 }),
    defineField({ name: 'storyTextLv', title: 'Our Story Text (LV)', type: 'text', rows: 8 }),
    defineField({ name: 'valuesLabel', title: 'Values Label (EN)', type: 'string' }),
    defineField({ name: 'valuesLabelLv', title: 'Values Label (LV)', type: 'string' }),
    defineField({ name: 'valuesHeading', title: 'Values Heading (EN)', type: 'string' }),
    defineField({ name: 'valuesHeadingLv', title: 'Values Heading (LV)', type: 'string' }),
    defineField({
      name: 'values', title: 'Values', type: 'array',
      of: [{ type: 'object', fields: [
        defineField({ name: 'icon', title: 'Emoji Icon', type: 'string' }),
        defineField({ name: 'title', title: 'Title (EN)', type: 'string' }),
        defineField({ name: 'titleLv', title: 'Title (LV)', type: 'string' }),
        defineField({ name: 'description', title: 'Description (EN)', type: 'text', rows: 2 }),
        defineField({ name: 'descriptionLv', title: 'Description (LV)', type: 'text', rows: 2 }),
      ], preview: { select: { title: 'title', subtitle: 'icon' } } }],
    }),
    defineField({ name: 'numbersLabel', title: 'Numbers Label (EN)', type: 'string' }),
    defineField({ name: 'numbersLabelLv', title: 'Numbers Label (LV)', type: 'string' }),
    defineField({ name: 'numbersHeading', title: 'Numbers Heading (EN)', type: 'string' }),
    defineField({ name: 'numbersHeadingLv', title: 'Numbers Heading (LV)', type: 'string' }),
    defineField({
      name: 'stats', title: 'Stats', type: 'array',
      of: [{ type: 'object', fields: [
        defineField({ name: 'value', title: 'Number/Value', type: 'string' }),
        defineField({ name: 'label', title: 'Label (EN)', type: 'string' }),
        defineField({ name: 'labelLv', title: 'Label (LV)', type: 'string' }),
      ], preview: { select: { title: 'value', subtitle: 'label' } } }],
    }),
    defineField({ name: 'ctaHeading', title: 'CTA Heading (EN)', type: 'string' }),
    defineField({ name: 'ctaHeadingLv', title: 'CTA Heading (LV)', type: 'string' }),
    defineField({ name: 'ctaSubtitle', title: 'CTA Subtitle (EN)', type: 'string' }),
    defineField({ name: 'ctaSubtitleLv', title: 'CTA Subtitle (LV)', type: 'string' }),
    defineField({ name: 'ctaBtn1', title: 'CTA Button 1 (EN)', type: 'string' }),
    defineField({ name: 'ctaBtn1Lv', title: 'CTA Button 1 (LV)', type: 'string' }),
    defineField({ name: 'ctaBtn2', title: 'CTA Button 2 (EN)', type: 'string' }),
    defineField({ name: 'ctaBtn2Lv', title: 'CTA Button 2 (LV)', type: 'string' }),
  ],
  preview: { prepare() { return { title: 'About Page' } } },
})
